sites:
  - name: "ARD"
    url: "https://www.ardmediathek.de/filme"
    title: "Die besten Filme in der ARD"
    description: "Die Filme der ARD im Überblick: Von Krimis, Komödien, Arthouse- und Liebesfilmen bis zu Märchen und spannenden Debütfilmen."
    selector:
      item: "div[itemType='https://schema.org/Movie']"
      link: "href@a"
      title: "h3"
      description: ""
  - name: "ZDF"
    url: "https://www.zdf.de/spielfilm-highlights-104"
    title: "ZDF Spielfilm-Highlights"
    description: "Internationale Filme mit spannenden und emotionalen Geschichten. Ob Krimi, Drama, Komödie, Lovestory oder Thriller, für jeden Geschmack wird etwas geboten."
    selector:
      item: "div[data-testid='teaser-tile']"
      link: "href@a"
      title: "h3"
      description: ""
  - name: "Arte"
    url: "https://www.arte.tv/de/videos/kino/filme/"
    title: "Arte Kinofilme"
    description: "Kultfilme, Autorenfilme, Stummfilme – Entdecken Sie die Vielfalt des ARTE-Filmangebots."
    selector:
      item: "div[data-testid='ts-tsItem']"
      link: "href@a"
      title: "h3"
      description: ""
